### ISSUE TITLE
ERROR: Failed to connect to Alerta API due to missing or invalid config.json file.

### ISSUE THREAD

**Issue by corvus-ch** [alerta/vagrant-try-alerta#19]
**Issue Summary**

Running `vagrant up alerta` does not result in a functional setup.

**Environment**
- OS: Mac, Windows
- API version: unknown
- Deployment: VirtualBox 6.1
- For self-hosted, WSGI environment: apache/mod_wsgi

- Database: MongoDB

- Server config:
  Auth enabled? ???
  Auth provider? ???
  Customer views? ???
  (or provide the `/config` endpoint output)

- web UI version: ???
- CLI version: ???

**To Reproduce**
1. Clone this repository
2. Run `vagrant up alerta`
3. Open http://192.168.0.100/
4. An error message with the following text appears:

> ERROR: Failed to connect to Alerta API due to missing or invalid config.json file.
> Please confirm a config.json file exists, contains an "endpoint" setting and is in the same directory as the application index.html file.

**Expected behavior**
Alerta UI gets displayed.

**To Reproduce 2**
1. Clone this repository
2. Run `vagrant up alerta`
3. Run `vagrant ssh alerta`
4. Run `alerta send -r web01 -e NodeDown -s major -S Web -E Production -t "Server down."`

```
Error: Failed to get config from http://localhost:8080/config. Reason: 500 Server Error: Internal Server Error for url: http://localhost:8080/config
```

**Expected behavior**
A new alert gets sent to the API.

**Comment by satterly** [comment]
Thanks for reporting. 👍
